---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Archive the files
  archive:
    path: "{{ sphinx_build_dir }}/html/"
    dest: "{{ sphinx_build_dir }}/src.zip"
    format: zip
  delegate_to: localhost
  become: false

- name: Clean artifact path
  file:
    state: absent
    path: "{{ local_www_path }}/{{ deploy_dir }}/{{ docs_version }}"
  become: true

- name: Create a directory for docs on host if it does not exist
  ansible.builtin.file:
    path: "{{ local_www_path }}/{{ deploy_dir }}/{{ docs_version }}"
    state: directory
    mode: '0755'
    owner: nrp
    group: www-data
  become: true

- name: Extract files to host
  ansible.builtin.unarchive:
    src: "{{ sphinx_build_dir }}/src.zip"
    dest: "{{ local_www_path }}/{{ deploy_dir }}/{{ docs_version }}"
    owner: nrp
    group: www-data
  become: true

- name: Give link to the location of the pages
  local_action: 
    module: copy 
    content: "{{ docs_url }}/{{ deploy_dir }}/{{ docs_version }}/nrp-core/index.html"
    dest: destination.txt

- name: Clean artifact path
  file:
    state: absent
    path: "{{ local_www_path }}/{{ deploy_dir }}/{{ docs_version }}/src.zip"
  become: true

- name: Link latest version
  file:
    path: "{{ local_www_path }}/{{ latest_dir }}"
    src: "{{ local_www_path }}/{{ deploy_dir }}/{{ docs_version }}"
    state: link
    owner: nrp
    group: www-data
    force: yes
  become: true
  when: link_latest|bool == true